# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get golang.org/x/vgo
      - run: vgo build
  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get golang.org/x/vgo
      - run: vgo test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get golang.org/x/vgo
      - run: go get github.com/tcnksm/ghr
      - run: go get github.com/mitchellh/gox
      - run: mkdir dist
      - run: gox -output "dist/sum_{{.OS}}_{{.Arch}}"
      - run: ghr $(cat version.txt) ./dist && echo Done || echo No release
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

